# Código Auxiliar para a Segunda Avaliação.

In [1]:
import pandas as pd
import sqlite3

In [ ]:
AUTORES = ['Abner Blota Rodrigues', 'Diogo Vieira dos Santos']

As funções definidas abaixo, devem ser usada para acessar o banco de dados `bilheteria.db` e retornar os dados necessários para a resolução dos exercícios.

In [6]:
def carrega_tabela(database, tabela):
    '''
    Carrega uma tabela de um banco de dados 
    SQLite em um DataFrame do Pandas.
    Parâmetros:
    database: str - Caminho para o arquivo do banco de dados SQLite.
    tabela: str - Nome da tabela a ser carregada.
    '''
    with sqlite3.connect(database) as conn:
        query = f"SELECT * FROM {tabela}"
        df = pd.read_sql_query(query, conn)
    return df

In [7]:
def lista_tabelas(db_filename):
    '''
    Lista todas as tabelas em um banco de dados SQLite.
    Parâmetros:
    db_filename: str - Caminho para o arquivo do banco de dados SQLite.
    Retorna:
    DataFrame com os nomes das tabelas e suas contagens de linhas.
    '''
    # Connect to the SQLite database
    # conn = sqlite3.connect(db_filename)
    with sqlite3.connect(db_filename) as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
        tables = cursor.fetchall()

        table_row_counts = []
        for table in tables:
            table_name = table[0]
            query = f"SELECT COUNT(*) FROM {table_name};"
            cursor.execute(query)
            row_count = cursor.fetchone()[0]
            table_row_counts.append({"Table": table_name, "Row_Count": row_count})

        return pd.DataFrame(table_row_counts)

## Exemplos de uso das funções

In [9]:
lista_tabelas('bilheteria.db')

            Table  Row_Count
0   distribuidora         72
1           filme        515
2  grupo_exibidor         64
3        exibidor        180
4        complexo        683
5            sala       3231
6          sessao    1748363

In [ ]:
data_frame = carrega_tabela('bilheteria.db','sessao')
display(data_frame)

In [ ]:
sessao = carrega_tabela('bilheteria.db', 'sessao')
sessao.data_exibicao = pd.to_datetime(sessao.data_exibicao, format='%d/%m/%Y')
sessao

## PARTE 1: Análise exploratória dos dados

In [ ]:
# Questão 1: Qual o total de bilheteria de todos os filmes, ou seja, o público que foi aos filmes listados?
# Criando um banco de dados

bd_filmes = carrega_tabela('bilheteria.db','filme')
bd_sessao = carrega_tabela('bilheteria.db','sessao')

indice_filmes = []
bilheteria_filme = [0 for i in range(0,515)]

for i in range(0,515):
    indice_filmes.append(bd_filmes.loc[i,'titulo_original'])

for i in range(0,1748363):
    publico = bd_sessao.loc[i,'publico']
    bilheteria_filme[bd_sessao.loc[i,'filme_id']-1] += publico

dados = {
    "Nome_filme" : indice_filmes,
    "Bilheteria" : bilheteria_filme
}

df_bilheteria = pd.DataFrame(dados)

In [ ]:
# Questão 1: resolução
resultado = sum(bilheteria_filme)
print(resultado)

110153083
{'Nome_filme': ['DURVAL DISCOS', 'NOSSO LAR', 'REMOÇÃO', 'HOJE EU QUERO VOLTAR SOZINHO', 'O HOMEM DE LAGOA SANTA', 'CLARICE LISPECTOR - A DESCOBERTA DO MUNDO', 'UM FILME DE CINEMA', "PARA'Í", 'MÃE', 'MIRANTE', 'A TERRA NEGRA DOS KAWA', 'PROPRIEDADE', 'CRÔNICA DE UMA CIDADE PARTIDA', 'ADONIRAN, MEU NOME É JOÃO RUBINATO', 'SEUS OSSOS E SEUS OLHOS', 'DESTINO DAS SOMBRAS', 'DEPOIS DE SER CINZA', 'SEGUNDO TEMPO', 'LINHA DE FRENTE', 'O HOMEM CORDIAL', 'FRANCO NO TREM DO MEDO', 'A CIDADE DOS ABISMOS', 'PARA ONDE VOAM AS FEITICEIRAS', 'MATO SECO EM CHAMAS', 'NADA É POR ACASO', 'ALÉM DA LENDA - FILME', 'MARES DO DESTERRO', 'POROPOPÓ', 'NAS ONDAS DA FÉ', 'O RIO DO DESEJO', 'MARTE UM', 'LUZ NOS TRÓPICOS', 'MIÚDA E O GUARDA-CHUVA', 'PEQUENOS GUERREIROS', 'OLHA PRA ELAS', 'DETETIVES DO PRÉDIO AZUL 3 - UMA AVENTURA NO FIM DO MUNDO', 'JAIR RODRIGUES - DEIXA QUE DIGAM', 'NATUREZA MORTA', 'O ESPAÇO INFINITO', 'A RUPTURA', 'A ALMA QUER VOAR', 'O ACIDENTE', 'A PRIMEIRA MORTE DE JOANA', 'ALDEIA NATAL', 'A MÃE', 'MÁQUINA DO DESEJO', 'BALA SEM NOME', 'TINNITUS', 'LA PARLE', 'CANÇÃO AO LONGE', 'MURIBECA', 'SOL', 'LUIZ CARLINI - GUITARRISTA DE ROCK', 'AS ÓRFÃS DA RAINHA', 'QUANDO FALTA O AR', 'BEM VINDOS DE NOVO', 'CHEF JACK, O COZINHEIRO AVENTUREIRO', 'ALÉM DE NÓS', 'UM SAMURAI EM SÃO PAULO', 'PELE', 'RAQUEL 1:1', 'SINFONIA DE UM HOMEM COMUM', 'BIOCÊNTRICOS', 'NOITES ALIENÍGENAS', 'PLAUTO, UM  SOPRO MUSICAL', 'O MESTRE DA FUMAÇA', 'VAI E VEM', 'BEM-VINDA A QUIXERAMOBIM', 'UÝRA – A RETOMADA DA FLORESTA', 'A LASANHA ASSASSINA - A REVOLTA DAS MASSAS', 'CASA VAZIA', 'O ALECRIM E O SONHO', 'BARRACO DE FAMÍLIA', 'A PORTA AO LADO', 'A ÚLTIMA FESTA', 'TEMPOS DE BARBÁRIE - ATO I: TERAPIA DA VINGANÇA', 'TRÊS TIGRES TRISTES', 'MÔA, RAIZ AFRO MÃE', 'NA RÉDEA CURTA', 'ME CHAMA QUE EU VOU', 'ENEIDA', 'A ILHA DOS ILÚS', 'FERVO', 'O AMOR DÁ VOLTAS', 'MEDUSA', 'BRICHOS 3 - MEGAVIRUS', 'MUCO : CONTRADIÇÃO DA TRADIÇÃO', 'OTTO: DE TRÁS P/ DIANTE', 'A PRAGA', 'UM JÓQUEI CEARENSE NA COREIA', 'MULEQUE TÉ DOIDO 4 - MORREU MARIA PREÁ!', 'DESAPEGA', 'PERLIMPS', 'REGRA 34', 'ANDANÇA - OS ENCONTROS E AS MEMÓRIAS DE BETH CARVALHO', 'VAI CORINTHIANS!', 'NIOBE', 'ENALDINHO E O MISTÉRIO DA LAGOA.', 'RAMA PANKARARU', 'RIO, NEGRO', 'MEMÓRIA SUFOCADA', 'LA SITUACIÓN', 'TIA VIRGÍNIA', 'CORPOLÍTICA', 'DOS 3 AOS 3', 'INCOMPATÍVEL COM A VIDA', 'O CIRCO VOLTOU', 'DIGA O QUE QUISER! EU VOU SER FELIZ A BEÇA!', 'RIO DOCE', 'VAI TER TROCO', 'O PASTOR E O GUERRILHEIRO', 'NINGUÉM É DE NINGUÉM', 'TIRE 5 CARTAS', 'VIDAS DESCARTÁVEIS', 'TENHO FÉ', 'BEM-VINDA VIOLETA', 'AS TRÊS VIDAS DE FRIEDA WOLFF', 'URUBUS', 'CAPITU E O CAPITULO', 'DERRAPADA', 'ELIS & TOM, SÓ TINHA DE SER COM VOCÊ', 'TRAÇÃO', 'QUANTOS DIAS. QUANTAS NOITES', 'UM DIA CINCO ESTRELAS', 'MEU NOME É GAL', 'OS AVENTUREIROS - A ORIGEM', 'MARINHEIRO DAS MONTANHAS', 'PERDIDA', 'DESTINOS OPOSTOS', 'RODEIO ROCK', 'REVOLTA DOS MALÊS', 'ESTRANHO CAMINHO', 'A ERA DOS HUMANOS', 'TPM! MEU AMOR', 'O PORTEIRO', 'RETRATOS FANTASMAS', 'UM POUCO DE MIM, UM POUCO DE NÓS', 'ROBERTO FARIAS:  MEMÓRIAS DE UM CINEASTA', 'PÉROLA', 'EU SOU MARIA', 'CAFI', 'PEDÁGIO', 'ANGELA', 'NOSSO SONHO', 'FLUXO', 'STAND UP MINHA VIDA É UMA PIADA', 'NÃO SEI QUANTAS ALMAS TENHO', 'NÃO TEM VOLTA', 'LOS DELINCUENTES', 'ATO FINAL', 'UMA FADA VEIO ME VISITAR', 'TÁ ESCRITO', 'MUSSUM, O FILMIS', 'NELSON PEREIRA DOS SANTOS - VIDA DE CINEMA', 'A BELA AMÉRICA', 'UMA CARTA PARA PAPAI NOEL', 'Ó PAÍ, Ó 2', 'AS AVENTURAS DE POLIANA - O FILME', 'ROSA DE SARON IN CONCERT', 'MINHA IRMÃ E EU', 'O SEQUESTRO DO VOO 375', 'PUAN', 'MAMONAS ASSASSINAS O FILME', 'A FLOR DO BURITI', 'O ESTRANHO', 'JOHN WICK', 'TOY STORY', 'THE LOST BOYS', 'THE LORD OF THE RINGS : THE RETURN OF THE KING', 'THE DEPARTED', 'GOODFELLAS', 'THE EXORCIST', 'DOG DAY AFTERNOON', 'HARRY POTTER AND THE CHAMBER OF SECRETS', "HARRY POTTER AND THE PHILOSOPHER'S STONE", 'BONNIE & CLYDE', 'THE SHINING', 'BLADE RUNNER', 'THE TWILIGHT SAGA: BREAKING DAWN PART 2', 'FRIDAY THE 13TH', 'TITANIC', 'NIGHTMARE ON ELM STREET', 'SHORTBUS', 'TWILIGHT', '2001 : A SPACE ODYSSEY', 'JOHN WICK: CHAPTER 2', 'FANTASTIC BEASTS: THE CRIMES OF GRINDELWALD', 'CLÍMAX', 'JOHN WICK 3: PARABELLUM', 'MIDSOMMAR', 'ANNABELLE COMES HOME', 'IT: CHAPTER TWO', 'DOCTOR SLEEP', 'THE FATHER', 'RED SHOES AND THE SEVEN DWARF', 'THE CROODS: A NEW AGE', 'THE BOSS BABY: FAMILY BUSINESS', 'AINBO - THE SPIRIT OF THE AMAZON', 'NARDJES A.', 'DEMON SLAYER: MUGEN TRAIN', 'SPACE JAM: A NEW LEGACY', 'PAW PATROL: THE MOVIE', 'CLIFFORD THE BIG RED DOG', 'SPIDER-MAN: NO WAY HOME', 'ENCANTO', 'SING 2', 'SCREAM', 'UNCHARTED', 'THE BAD GUYS', 'OPERATION FORTUNE: RUSE DE GUERRE', 'JUJUTSU KAISEN 0: THE MOVIE', 'FANTASTIC BEASTS: THE SECRETS OF DUMBLEDORE', 'SONIC THE HEDGEHOG 2', 'ELVIS', 'MINIONS: THE RISE OF GRU', 'JURASSIC WORLD: DOMINION', 'DC LEAGUE OF SUPERPETS', 'EVERYTHING EVERYWHERE ALL AT ONCE', 'TOP GUN: MAVERICK', 'BEAST', 'LISA REDLER', 'DRAGON BALL SUPER: SUPER HERO', 'THE ROUNDUP', 'LYLE, LYLE, CROCODILE', 'PAWS OF FURY: THE LEGEND OF HANK', 'MRS. HARRIS GOES TO PARIS', 'SMILE', 'SPIDER-MAN: NO WAY HOME', 'BLACK ADAM', 'SHAZAM! FURY OF THE GODS', 'SHE SAID', 'EMILY', 'ARMAGEDDON TIME', 'TAD THE LOST EXPLORER AND THE EMERALD TABLET', 'I WANNA DANCE WITH SOMEBODY', 'VIOLENT NIGHT', 'CORAZON DE PADRE', 'CZYSCIEC', 'DEVOTION', 'FOURMI', 'MADRE TERESA - NO GREATER LOVE', 'OUR LADY OF THE NILE', 'BONES AND ALL', 'WHITE NOISE', 'A MAN CALLED OTTO', 'TILL', 'BLACK PANTHER: WAKANDA FOREVER', 'LE TRÉSOR DU PETIT NICOLAS', 'TRIANGLE OF SADNESS', 'DECISION TO LEAVE', 'TWIST À BAMAKO', 'TÁR', 'AFTERSUN', 'PINOCCHIO', 'PLANE', 'PUSS IN BOOTS: THE LAST WISH', 'RIEN À FOUTRE', 'UNE FEMME DU MONDE', 'TERRIFIER 2', 'MASCARADE', 'M3GAN', 'BABYLON', 'THE AMAZING MAURICE', 'JOHN WICK: CHAPTER 4', 'BEAUTIFUL DISASTER', '13 EXORCISMOS', 'FIREBIRD', 'HUNT', 'AVATAR: THE WAY OF WATER', 'JEEPERS CREEPERS: REBORN', 'PROJECT GEMINI', 'CORSAGE', "TCHAIKOVSKY'S WIFE", 'THE FABELMANS', 'LES PROMESSES', 'PEARL', 'THE SON', "THE TIGER'S NEST", 'LA BRIGADE', 'MISSING', 'HOW TO PLEASE A WOMAN', 'THE BANSHEES OF INISHERIN', 'THE DEVIL CONSPIRACY', 'BOY FROM HEAVEN', 'CREED III', 'IL COLIBRI', 'MUMMIES', 'CLOSE', 'HOLY SPIDER', 'BED REST', 'MAYBE I DO', 'LIEBESDINGS', 'MY NEIGHBOR ADOLF', 'MARLOWE', 'KNOCK AT THE CABIN', 'THE OFFERING', 'BROKER', 'ROCK DOG 3: BATTLE THE BEAT', 'MATAR A PINOCHET', "GOD'S CREATURES", 'MY FATHER HISTORIES', 'THE TEXAS CHAIN SAW MASSACRE', 'THE WHALE', 'THE THREE MUSKETEERS: D’ARTAGNAN', 'ANT-MAN AND THE WASP: QUANTUMANIA', 'COCAINE BEAR', 'GOLDA', 'DEATH OF NINTENDO', 'HOURIA', 'LA NIÑA DE LA COMUNIÓN', 'UNE JEUNE FILLE QUI VA BIEN', '65', 'LEFT BEHIND: RISE OF THE ANTICHRIST', 'WOMEN TALKING', 'TWO WITCHES', 'BEAU IS AFRAID', 'EVIL DEAD RISE', 'DUNGEONS & DRAGONS: HONOR AMONG THIEVES', 'LOVE AGAIN', 'SCREAM VI', 'THE POPE´S EXORCIST', 'HEAVEN IN HELL', 'CONSECRATION', 'THE SUPER MARIO BROS. MOVIE', 'DEMON SLAYER: TO THE SWORDSMITH VILLAGE', 'AIR', 'SPINNING GOLD', 'BOOK CLUB: THE NEXT CHAPTER', 'FAST X', 'RENFIELD', 'BOY GEORGE AND CULTURE CLUB “ONE WORLD, ONE LOVE”', 'RODEO', 'SONS OF RAMSÉS', 'THE FIVE DEVILS', 'EN ROUE LIBRE', 'IN FROM THE SIDE', 'ONE TRUE LOVES', 'SEA OF TIME', 'SKINAMARINK', 'THE BLACK DEMON', 'MAFIA MAMMA', 'THE RITUAL KILLER', 'SUZUME', 'SPIDER-MAN: ACROSS THE SPIDER-VERSE', 'CHAMPIONS', 'KANDAHAR', 'THE NIGHT 12TH', 'STRAYS', 'FINNICK', 'SADAKO DX', 'PACIFICTION', 'KNIGHTS OF THE ZODIAC', 'LOST TRANSPORT', 'À PROPOS DE JOAN', 'NO BEARS', 'THE PORTABLE DOOR', 'EL ULTIMO LLAMADO DE MARÍA', 'EVOLUTION', 'ABOUT MY FATHER', 'THE LITTLE MERMAID', 'THE BOOK OF WONDERS', 'NO HARD FEELINGS', 'GUARDIANS OF THE GALAXY VOL. 3', 'ARGONUTS', 'INSIDIOUS: THE RED DOOR', 'THE LAST BUS', 'THE STORY OF MY WIFE', 'EO', 'JOY RIDE', 'NOS LEVANTAREMOS AL ALBA', 'AFTER EVERYTHING', 'TALK TO ME', 'TO CATCH A KILLER (MISANTHROPE)', 'THE FLASH', 'MEDUSA DELUXE', 'PASSAGES', 'ROGER WATERS LIVE - THIS IS NOT A DRILL', 'EQUALIZER 3', 'GRAN TURISMO', 'TRANSFORMERS: RISE OF THE BEASTS', 'SWORD ART ONLINE THE MOVIE - PROGRESSIVE- SCHERZO OF DEEP NIGHT', 'THE BOOGEYMAN', 'TOMORROW X TOGETHER WORLD TOUR ACT: SWEET MIRAGE IN LA : LIVE VIEWING', 'ASTEROID CITY', 'THE LAST VOYAGE OF THE DEMETER', 'OPPENHEIMER', 'RUBY GILLMAN TEENAGE KRAKEN', "SUGA - AGUST D TOUR 'D-DAY' IN JAPAN: LIVE VIEWING", 'ELEMENTAL', 'CATS IN THE MUSEUM', 'LA SYNDICALISTE', 'J-HOPE IN THE BOX', 'SUGA: ROAD TO D-DAY', 'MISSION: IMPOSSIBLE - DEAD RECKONING PART ONE', 'INDIANA JONES AND THE DIAL OF DESTINY', 'MON CRIME', 'THE EXPENDABLES 4', 'IT LIVES INSIDE', 'BARBIE', 'BLUE BEETLE', 'BLUE JEAN', 'FOGO FÁTUO', 'THE MEG 2', 'TIRAILLEURS', 'WONKA', 'ALL FUN AND GAMES', 'MAVKA: THE FOREST SONG', 'RHEINGOLD', 'WINNIE-THE-POOH: BLOOD AND HONEY', 'RETRIBUTION', 'HYPNOTIC', 'ONDE FICA ESTA RUA? OU SEM ANTES NEM DEPOIS', 'DISCO BOY', 'ALMA VIVA', 'TERRA QUE MARCA', 'ÁGUAS DO PASTAZA', 'THE HAUNTING OF THE QUEEN MARY', 'HAUNTED MANSION', 'THE FIRST SLAM DUNK', 'LA DERNIÈRE REINE', 'THE ESTATE', 'BLACKBERRY', 'ZEBY NIE BYLO SLADÓW', 'EL CIELO NO PUEDE ESPER@R', 'SAINT MICHAEL - MEET THE ANGEL', 'LAILA IN HAIFA', '97 MINUTES', 'WILDFLOWER', 'MY FAIRY TROUBLEMAKER', 'QUICKSAND', 'TEENAGE MUTANT NINJA TURTLES: MUTANT MAYHEM', 'THE DIVE', 'ITHAKA', 'LE OTTO MONTAGNE', 'MAMAMOO: MY CON THE MOVIE', 'KANG DANIEL: MY PARADE', 'ODESZA: THE LAST GOODBYE CINEMATIC EXPERIENCE', 'AN CAILÍN CIÚIN', 'DUMB MONEY', 'NAPOLEON', 'COBWEB', 'JULES', 'VIDBLYSK', 'RIDE ON', 'TELL IT LIKE A WOMAN', 'METALLICA M72 WORLD TOUR LIVE FROM TX NIGHT ONE', 'A HAUNTING IN VENICE', 'ARISTOTLE AND DANTE DISCOVER THE SECRET OF THE UNIVERSE', 'SAW X', 'IL BOEMO', 'SOUND OF FREEDOM', 'THANKSGIVING', 'THE CREATOR', "THE MARSH KING'S DAUGHTER", 'THE NUN 2', 'THE EXORCIST: BELIEVER', 'BANK OF DAVE', "FIVE NIGHTS AT FREDDY'S", 'AQUAMAN AND THE LOST KINGDOM', 'TROLLS BAND TOGETHER', 'CARLOS: THE SANTANA JOURNEY GLOBAL PREMIERE', 'EXTRAÑA FORMA DE VIDA', 'GLUPCY', 'IU CONCERT: THE GOLDEN HOUR', 'LA MAISON', 'ARRÊTE AVEC TES MENSONGES', 'NEFARIOUS', 'OLDBOY', 'KILLERS OF THE FLOWER MOON', 'NYAD', 'PAW PATROL: THE MIGHTY MOVIE', 'NOSTALGIA', 'LES ENFANTS DES AUTRES', 'LILLE ALLAN - DEN MENNESKELIGE ANTENNE', 'LES ÂMES SOEURS', 'LE NOUVEAU JOUET', 'THEY SHOT THE PIANO PLAYER', 'BRADO', 'MY BIG FAT GREEK WEDDING 3', 'THE KILLER', 'TAYLOR SWIFT - THE ERAS TOUR', 'THE MARVELS', 'EL AÑO DEL TIGRE', 'KAIBUTSU', 'MAESTRO', 'RABIN, THE LAST DAY', 'THE NUTCRACKER AND THE MAGIC FLUTE', 'LA STRANEZZA', 'LEONORA ADDIO', 'FALLEN LEAVES', 'HOW TO HAVE SEX', 'ROTER HIMMEL', 'SAMSARA', 'LORD OF MISRULES', 'SILENT NIGHT', 'THE HUNGER GAMES – BALLAD OF SONGBIRDS AND SNAKES', 'PICCOLO CORPO', 'LE RETOUR', 'MIGRATION', 'LE THÉORÈME DE MARGUERITE', "L'ÉTÉ DERNIER", 'DIGIMON ADVENTURE 02: THE BEGINNING', 'LA SOCIEDAD DE LA NIEVE', 'THE THREE MUSKETEERS: MILADY', 'THE MEAN ONE', 'GODZILLA MINUS ONE', 'NEXT GOAL WINS', 'RENAISSANCE: A FILM BY BEYONCÉ', 'SOFTIE', 'LA LIGNE', 'NCT NATION: TO THE WORLD IN CINEMAS', 'JOURNEY TO BETHLEHEM', 'PRISCILLA', "SEVENTEEN TOUR 'FOLLOW' TO JAPAN: LIVE VIEWING", 'THE CHOSEN'], 'Bilheteria': [np.int64(825), np.int64(23090), np.int64(90), np.int64(18), np.int64(531), np.int64(1104), np.int64(3048), np.int64(1226), np.int64(44), np.int64(5), np.int64(254), np.int64(1409), np.int64(186), np.int64(41), np.int64(263), np.int64(48), np.int64(211), np.int64(323), np.int64(27), np.int64(2653), np.int64(3367), np.int64(607), np.int64(491), np.int64(677), np.int64(48), np.int64(9), np.int64(108), np.int64(256), np.int64(36065), np.int64(4283), np.int64(4237), np.int64(31), np.int64(8), np.int64(3), np.int64(100), np.int64(359), np.int64(1190), np.int64(83), np.int64(123), np.int64(28), np.int64(23), np.int64(32), np.int64(2255), np.int64(171), np.int64(25), np.int64(2105), np.int64(4), np.int64(894), np.int64(186), np.int64(554), np.int64(40), np.int64(25), np.int64(59), np.int64(2089), np.int64(5049), np.int64(1215), np.int64(47591), np.int64(277), np.int64(277), np.int64(77), np.int64(294), np.int64(15), np.int64(2944), np.int64(1918), np.int64(61), np.int64(1330), np.int64(400), np.int64(1400), np.int64(108), np.int64(74), np.int64(215), np.int64(16), np.int64(950), np.int64(740), np.int64(1608), np.int64(2758), np.int64(433), np.int64(900), np.int64(2427), np.int64(522), np.int64(524), np.int64(601), np.int64(10958), np.int64(488), np.int64(898), np.int64(292), np.int64(2937), np.int64(117), np.int64(382), np.int64(64), np.int64(13618), np.int64(151417), np.int64(1281), np.int64(4043), np.int64(6474), np.int64(1792), np.int64(237), np.int64(47768), np.int64(85), np.int64(428), np.int64(506), np.int64(9276), np.int64(4140), np.int64(735), np.int64(2079), np.int64(283), np.int64(50), np.int64(126), np.int64(212), np.int64(4683), np.int64(1920), np.int64(132529), np.int64(13924), np.int64(236), np.int64(104), np.int64(1891), np.int64(159), np.int64(2815), np.int64(1371), np.int64(214), np.int64(56536), np.int64(1081), np.int64(1586), np.int64(17198), np.int64(135517), np.int64(392615), np.int64(1321), np.int64(91467), np.int64(308), np.int64(8279), np.int64(629), np.int64(23), np.int64(10), np.int64(484), np.int64(45507), np.int64(30251), np.int64(99), np.int64(80), np.int64(6753), np.int64(436), np.int64(219), np.int64(5794), np.int64(14536), np.int64(485818), np.int64(44), np.int64(142), np.int64(409), np.int64(18996), np.int64(1197), np.int64(193), np.int64(62278), np.int64(53922), np.int64(201346), np.int64(310), np.int64(107), np.int64(5210), np.int64(176688), np.int64(96468), np.int64(4832), np.int64(270635), np.int64(190072), np.int64(2244), np.int64(169976), np.int64(56), np.int64(73), np.int64(254), np.int64(23), np.int64(66), np.int64(4101), np.int64(89), np.int64(298), np.int64(56), np.int64(31), np.int64(77), np.int64(145), np.int64(136), np.int64(42), np.int64(353), np.int64(7245), np.int64(52), np.int64(467314), np.int64(67), np.int64(527), np.int64(112), np.int64(795), np.int64(230), np.int64(40), np.int64(130), np.int64(288), np.int64(81), np.int64(4533), np.int64(4190), np.int64(17), np.int64(85), np.int64(161), np.int64(970), np.int64(565), np.int64(155), np.int64(149), np.int64(7), np.int64(793), np.int64(665), np.int64(122), np.int64(493), np.int64(160), np.int64(2691), np.int64(23), np.int64(298), np.int64(1461), np.int64(120548), np.int64(303), np.int64(828), np.int64(2336), np.int64(667), np.int64(7733), np.int64(2176), np.int64(3737), np.int64(110481), np.int64(1586), np.int64(81), np.int64(20), np.int64(145), np.int64(5), np.int64(5986), np.int64(222), np.int64(100), np.int64(1903), np.int64(565), np.int64(421), np.int64(902351), np.int64(199), np.int64(13586), np.int64(163), np.int64(1189), np.int64(248636), np.int64(105), np.int64(65135), np.int64(2744), np.int64(189), np.int64(8), np.int64(419), np.int64(541), np.int64(144), np.int64(5), np.int64(293427), np.int64(12863), np.int64(99088), np.int64(4659), np.int64(34565), np.int64(12286), np.int64(71), np.int64(45332), np.int64(23844), np.int64(23), np.int64(279708), np.int64(5358525), np.int64(40), np.int64(1), np.int64(202874), np.int64(1386), np.int64(1648241), np.int64(83715), np.int64(87116), np.int64(2303687), np.int64(27364), np.int64(116159), np.int64(2469), np.int64(2102), np.int64(5631389), np.int64(65618), np.int64(32627), np.int64(5559), np.int64(10072), np.int64(103854), np.int64(1611), np.int64(104114), np.int64(13175), np.int64(20848), np.int64(2091), np.int64(85860), np.int64(482), np.int64(66405), np.int64(54300), np.int64(1481), np.int64(814341), np.int64(2083), np.int64(318765), np.int64(35626), np.int64(1648), np.int64(59097), np.int64(78549), np.int64(29), np.int64(7050), np.int64(5367), np.int64(314415), np.int64(329171), np.int64(6798), np.int64(25758), np.int64(251), np.int64(1669), np.int64(276), np.int64(1836), np.int64(409781), np.int64(103590), np.int64(2588946), np.int64(52410), np.int64(57628), np.int64(35), np.int64(1908), np.int64(28826), np.int64(2318), np.int64(230063), np.int64(156189), np.int64(26010), np.int64(10453), np.int64(27430), np.int64(1021664), np.int64(1046723), np.int64(67442), np.int64(1150220), np.int64(696010), np.int64(5800), np.int64(96714), np.int64(6235953), np.int64(148205), np.int64(175232), np.int64(8712), np.int64(32690), np.int64(6132354), np.int64(40259), np.int64(14), np.int64(264), np.int64(406), np.int64(393), np.int64(1384), np.int64(1677), np.int64(7796), np.int64(889), np.int64(1265), np.int64(27091), np.int64(19155), np.int64(9692), np.int64(44738), np.int64(3328797), np.int64(4619), np.int64(53356), np.int64(1303), np.int64(87596), np.int64(62627), np.int64(75422), np.int64(307), np.int64(243516), np.int64(1768), np.int64(9601), np.int64(3647), np.int64(26728), np.int64(21056), np.int64(532), np.int64(12046), np.int64(3987722), np.int64(5031), np.int64(141823), np.int64(4211764), np.int64(47309), np.int64(736537), np.int64(5038), np.int64(2104), np.int64(2251), np.int64(47512), np.int64(6568), np.int64(85002), np.int64(752308), np.int64(32743), np.int64(1825487), np.int64(1138), np.int64(4851), np.int64(5631), np.int64(665218), np.int64(406623), np.int64(1285056), np.int64(1953), np.int64(74456), np.int64(8054), np.int64(33210), np.int64(78502), np.int64(2808153), np.int64(100695), np.int64(14549), np.int64(3985017), np.int64(88021), np.int64(3063), np.int64(5296), np.int64(6851), np.int64(1820040), np.int64(964624), np.int64(12398), np.int64(474533), np.int64(148764), np.int64(10238598), np.int64(2015562), np.int64(1577), np.int64(500), np.int64(1197780), np.int64(2266), np.int64(1723012), np.int64(193315), np.int64(16406), np.int64(818), np.int64(27968), np.int64(39866), np.int64(135372), np.int64(127), np.int64(433), np.int64(1168), np.int64(110), np.int64(139), np.int64(60614), np.int64(108810), np.int64(4958), np.int64(936), np.int64(2258), np.int64(4971), np.int64(25), np.int64(32980), np.int64(37876), np.int64(1390), np.int64(4270), np.int64(2308), np.int64(79397), np.int64(3719), np.int64(673020), np.int64(15585), np.int64(976), np.int64(6052), np.int64(1075), np.int64(77), np.int64(251), np.int64(3944), np.int64(23277), np.int64(775802), np.int64(54447), np.int64(849), np.int64(311), np.int64(1114), np.int64(367), np.int64(7463), np.int64(277599), np.int64(9844), np.int64(912603), np.int64(486), np.int64(2597889), np.int64(163869), np.int64(270620), np.int64(16560), np.int64(2839181), np.int64(694281), np.int64(146), np.int64(2777366), np.int64(1331249), np.int64(1417672), np.int64(285), np.int64(23234), np.int64(341), np.int64(1042), np.int64(3521), np.int64(222), np.int64(8234), np.int64(7311), np.int64(418794), np.int64(132), np.int64(1385168), np.int64(1075), np.int64(859), np.int64(5226), np.int64(358), np.int64(1300), np.int64(2168), np.int64(175), np.int64(12293), np.int64(2525), np.int64(185601), np.int64(1188572), np.int64(157), np.int64(13478), np.int64(6087), np.int64(3451), np.int64(34267), np.int64(705), np.int64(280), np.int64(11459), np.int64(1148), np.int64(4200), np.int64(575), np.int64(6397), np.int64(24708), np.int64(1949600), np.int64(43), np.int64(169), np.int64(19), np.int64(991), np.int64(1444), np.int64(29377), np.int64(486), np.int64(19051), np.int64(1283), np.int64(216849), np.int64(2383), np.int64(153244), np.int64(233), np.int64(543), np.int64(4215), np.int64(8247), np.int64(7904), np.int64(6140), np.int64(114826)]}

In [42]:
# Preparo para a questão 2:
bilheteria_int = [int(x) for x in bilheteria_filme]

dic_bilheteria = dict(zip(indice_filmes,bilheteria_int))
print(dic_bilheteria)

{'DURVAL DISCOS': 825, 'NOSSO LAR': 23090, 'REMOÇÃO': 90, 'HOJE EU QUERO VOLTAR SOZINHO': 18, 'O HOMEM DE LAGOA SANTA': 531, 'CLARICE LISPECTOR - A DESCOBERTA DO MUNDO': 1104, 'UM FILME DE CINEMA': 3048, "PARA'Í": 1226, 'MÃE': 44, 'MIRANTE': 5, 'A TERRA NEGRA DOS KAWA': 254, 'PROPRIEDADE': 1409, 'CRÔNICA DE UMA CIDADE PARTIDA': 186, 'ADONIRAN, MEU NOME É JOÃO RUBINATO': 41, 'SEUS OSSOS E SEUS OLHOS': 263, 'DESTINO DAS SOMBRAS': 48, 'DEPOIS DE SER CINZA': 211, 'SEGUNDO TEMPO': 323, 'LINHA DE FRENTE': 27, 'O HOMEM CORDIAL': 2653, 'FRANCO NO TREM DO MEDO': 3367, 'A CIDADE DOS ABISMOS': 607, 'PARA ONDE VOAM AS FEITICEIRAS': 491, 'MATO SECO EM CHAMAS': 677, 'NADA É POR ACASO': 48, 'ALÉM DA LENDA - FILME': 9, 'MARES DO DESTERRO': 108, 'POROPOPÓ': 256, 'NAS ONDAS DA FÉ': 36065, 'O RIO DO DESEJO': 4283, 'MARTE UM': 4237, 'LUZ NOS TRÓPICOS': 31, 'MIÚDA E O GUARDA-CHUVA': 8, 'PEQUENOS GUERREIROS': 3, 'OLHA PRA ELAS': 100, 'DETETIVES DO PRÉDIO AZUL 3 - UMA AVENTURA NO FIM DO MUNDO': 359, 'JAIR RODRIGUES - DEIXA QUE DIGAM': 1190, 'NATUREZA MORTA': 83, 'O ESPAÇO INFINITO': 123, 'A RUPTURA': 28, 'A ALMA QUER VOAR': 23, 'O ACIDENTE': 32, 'A PRIMEIRA MORTE DE JOANA': 2255, 'ALDEIA NATAL': 171, 'A MÃE': 25, 'MÁQUINA DO DESEJO': 2105, 'BALA SEM NOME': 4, 'TINNITUS': 894, 'LA PARLE': 186, 'CANÇÃO AO LONGE': 554, 'MURIBECA': 40, 'SOL': 25, 'LUIZ CARLINI - GUITARRISTA DE ROCK': 59, 'AS ÓRFÃS DA RAINHA': 2089, 'QUANDO FALTA O AR': 5049, 'BEM VINDOS DE NOVO': 1215, 'CHEF JACK, O COZINHEIRO AVENTUREIRO': 47591, 'ALÉM DE NÓS': 277, 'UM SAMURAI EM SÃO PAULO': 277, 'PELE': 77, 'RAQUEL 1:1': 294, 'SINFONIA DE UM HOMEM COMUM': 15, 'BIOCÊNTRICOS': 2944, 'NOITES ALIENÍGENAS': 1918, 'PLAUTO, UM  SOPRO MUSICAL': 61, 'O MESTRE DA FUMAÇA': 1330, 'VAI E VEM': 400, 'BEM-VINDA A QUIXERAMOBIM': 1400, 'UÝRA – A RETOMADA DA FLORESTA': 108, 'A LASANHA ASSASSINA - A REVOLTA DAS MASSAS': 74, 'CASA VAZIA': 215, 'O ALECRIM E O SONHO': 16, 'BARRACO DE FAMÍLIA': 950, 'A PORTA AO LADO': 740, 'A ÚLTIMA FESTA': 1608, 'TEMPOS DE BARBÁRIE - ATO I: TERAPIA DA VINGANÇA': 2758, 'TRÊS TIGRES TRISTES': 433, 'MÔA, RAIZ AFRO MÃE': 900, 'NA RÉDEA CURTA': 2427, 'ME CHAMA QUE EU VOU': 522, 'ENEIDA': 524, 'A ILHA DOS ILÚS': 601, 'FERVO': 10958, 'O AMOR DÁ VOLTAS': 488, 'MEDUSA': 898, 'BRICHOS 3 - MEGAVIRUS': 292, 'MUCO : CONTRADIÇÃO DA TRADIÇÃO': 2937, 'OTTO: DE TRÁS P/ DIANTE': 117, 'A PRAGA': 382, 'UM JÓQUEI CEARENSE NA COREIA': 64, 'MULEQUE TÉ DOIDO 4 - MORREU MARIA PREÁ!': 13618, 'DESAPEGA': 151417, 'PERLIMPS': 1281, 'REGRA 34': 4043, 'ANDANÇA - OS ENCONTROS E AS MEMÓRIAS DE BETH CARVALHO': 6474, 'VAI CORINTHIANS!': 1792, 'NIOBE': 237, 'ENALDINHO E O MISTÉRIO DA LAGOA.': 47768, 'RAMA PANKARARU': 85, 'RIO, NEGRO': 428, 'MEMÓRIA SUFOCADA': 506, 'LA SITUACIÓN': 9276, 'TIA VIRGÍNIA': 4140, 'CORPOLÍTICA': 735, 'DOS 3 AOS 3': 2079, 'INCOMPATÍVEL COM A VIDA': 283, 'O CIRCO VOLTOU': 50, 'DIGA O QUE QUISER! EU VOU SER FELIZ A BEÇA!': 126, 'RIO DOCE': 212, 'VAI TER TROCO': 4683, 'O PASTOR E O GUERRILHEIRO': 1920, 'NINGUÉM É DE NINGUÉM': 132529, 'TIRE 5 CARTAS': 13924, 'VIDAS DESCARTÁVEIS': 236, 'TENHO FÉ': 104, 'BEM-VINDA VIOLETA': 1891, 'AS TRÊS VIDAS DE FRIEDA WOLFF': 159, 'URUBUS': 2815, 'CAPITU E O CAPITULO': 1371, 'DERRAPADA': 214, 'ELIS & TOM, SÓ TINHA DE SER COM VOCÊ': 56536, 'TRAÇÃO': 1081, 'QUANTOS DIAS. QUANTAS NOITES': 1586, 'UM DIA CINCO ESTRELAS': 17198, 'MEU NOME É GAL': 135517, 'OS AVENTUREIROS - A ORIGEM': 392615, 'MARINHEIRO DAS MONTANHAS': 1321, 'PERDIDA': 91467, 'DESTINOS OPOSTOS': 308, 'RODEIO ROCK': 8279, 'REVOLTA DOS MALÊS': 629, 'ESTRANHO CAMINHO': 23, 'A ERA DOS HUMANOS': 10, 'TPM! MEU AMOR': 484, 'O PORTEIRO': 45507, 'RETRATOS FANTASMAS': 30251, 'UM POUCO DE MIM, UM POUCO DE NÓS': 99, 'ROBERTO FARIAS:  MEMÓRIAS DE UM CINEASTA': 80, 'PÉROLA': 6753, 'EU SOU MARIA': 436, 'CAFI': 219, 'PEDÁGIO': 5794, 'ANGELA': 14536, 'NOSSO SONHO': 485818, 'FLUXO': 44, 'STAND UP MINHA VIDA É UMA PIADA': 142, 'NÃO SEI QUANTAS ALMAS TENHO': 409, 'NÃO TEM VOLTA': 18996, 'LOS DELINCUENTES': 1197, 'ATO FINAL': 193, 'UMA FADA VEIO ME VISITAR': 62278, 'TÁ ESCRITO': 53922, 'MUSSUM, O FILMIS': 201346, 'NELSON PEREIRA DOS SANTOS - VIDA DE CINEMA': 310, 'A BELA AMÉRICA': 107, 'UMA CARTA PARA PAPAI NOEL': 5210, 'Ó PAÍ, Ó 2': 176688, 'AS AVENTURAS DE POLIANA - O FILME': 96468, 'ROSA DE SARON IN CONCERT': 4832, 'MINHA IRMÃ E EU': 270635, 'O SEQUESTRO DO VOO 375': 190072, 'PUAN': 2244, 'MAMONAS ASSASSINAS O FILME': 169976, 'A FLOR DO BURITI': 56, 'O ESTRANHO': 73, 'JOHN WICK': 254, 'TOY STORY': 23, 'THE LOST BOYS': 66, 'THE LORD OF THE RINGS : THE RETURN OF THE KING': 4101, 'THE DEPARTED': 89, 'GOODFELLAS': 298, 'THE EXORCIST': 56, 'DOG DAY AFTERNOON': 31, 'HARRY POTTER AND THE CHAMBER OF SECRETS': 77, "HARRY POTTER AND THE PHILOSOPHER'S STONE": 145, 'BONNIE & CLYDE': 136, 'THE SHINING': 42, 'BLADE RUNNER': 353, 'THE TWILIGHT SAGA: BREAKING DAWN PART 2': 7245, 'FRIDAY THE 13TH': 52, 'TITANIC': 467314, 'NIGHTMARE ON ELM STREET': 67, 'SHORTBUS': 527, 'TWILIGHT': 112, '2001 : A SPACE ODYSSEY': 795, 'JOHN WICK: CHAPTER 2': 230, 'FANTASTIC BEASTS: THE CRIMES OF GRINDELWALD': 40, 'CLÍMAX': 130, 'JOHN WICK 3: PARABELLUM': 288, 'MIDSOMMAR': 81, 'ANNABELLE COMES HOME': 4533, 'IT: CHAPTER TWO': 4190, 'DOCTOR SLEEP': 17, 'THE FATHER': 85, 'RED SHOES AND THE SEVEN DWARF': 161, 'THE CROODS: A NEW AGE': 970, 'THE BOSS BABY: FAMILY BUSINESS': 565, 'AINBO - THE SPIRIT OF THE AMAZON': 155, 'NARDJES A.': 149, 'DEMON SLAYER: MUGEN TRAIN': 7, 'SPACE JAM: A NEW LEGACY': 793, 'PAW PATROL: THE MOVIE': 665, 'CLIFFORD THE BIG RED DOG': 122, 'SPIDER-MAN: NO WAY HOME': 565, 'ENCANTO': 160, 'SING 2': 2691, 'SCREAM': 23, 'UNCHARTED': 298, 'THE BAD GUYS': 1461, 'OPERATION FORTUNE: RUSE DE GUERRE': 120548, 'JUJUTSU KAISEN 0: THE MOVIE': 303, 'FANTASTIC BEASTS: THE SECRETS OF DUMBLEDORE': 828, 'SONIC THE HEDGEHOG 2': 2336, 'ELVIS': 667, 'MINIONS: THE RISE OF GRU': 7733, 'JURASSIC WORLD: DOMINION': 2176, 'DC LEAGUE OF SUPERPETS': 3737, 'EVERYTHING EVERYWHERE ALL AT ONCE': 110481, 'TOP GUN: MAVERICK': 1586, 'BEAST': 81, 'LISA REDLER': 20, 'DRAGON BALL SUPER: SUPER HERO': 145, 'THE ROUNDUP': 5, 'LYLE, LYLE, CROCODILE': 5986, 'PAWS OF FURY: THE LEGEND OF HANK': 222, 'MRS. HARRIS GOES TO PARIS': 100, 'SMILE': 1903, 'BLACK ADAM': 421, 'SHAZAM! FURY OF THE GODS': 902351, 'SHE SAID': 199, 'EMILY': 13586, 'ARMAGEDDON TIME': 163, 'TAD THE LOST EXPLORER AND THE EMERALD TABLET': 1189, 'I WANNA DANCE WITH SOMEBODY': 248636, 'VIOLENT NIGHT': 105, 'CORAZON DE PADRE': 65135, 'CZYSCIEC': 2744, 'DEVOTION': 189, 'FOURMI': 8, 'MADRE TERESA - NO GREATER LOVE': 419, 'OUR LADY OF THE NILE': 541, 'BONES AND ALL': 144, 'WHITE NOISE': 5, 'A MAN CALLED OTTO': 293427, 'TILL': 12863, 'BLACK PANTHER: WAKANDA FOREVER': 99088, 'LE TRÉSOR DU PETIT NICOLAS': 4659, 'TRIANGLE OF SADNESS': 34565, 'DECISION TO LEAVE': 12286, 'TWIST À BAMAKO': 71, 'TÁR': 45332, 'AFTERSUN': 23844, 'PINOCCHIO': 23, 'PLANE': 279708, 'PUSS IN BOOTS: THE LAST WISH': 5358525, 'RIEN À FOUTRE': 40, 'UNE FEMME DU MONDE': 1, 'TERRIFIER 2': 202874, 'MASCARADE': 1386, 'M3GAN': 1648241, 'BABYLON': 83715, 'THE AMAZING MAURICE': 87116, 'JOHN WICK: CHAPTER 4': 2303687, 'BEAUTIFUL DISASTER': 27364, '13 EXORCISMOS': 116159, 'FIREBIRD': 2469, 'HUNT': 2102, 'AVATAR: THE WAY OF WATER': 5631389, 'JEEPERS CREEPERS: REBORN': 65618, 'PROJECT GEMINI': 32627, 'CORSAGE': 5559, "TCHAIKOVSKY'S WIFE": 10072, 'THE FABELMANS': 103854, 'LES PROMESSES': 1611, 'PEARL': 104114, 'THE SON': 13175, "THE TIGER'S NEST": 20848, 'LA BRIGADE': 2091, 'MISSING': 85860, 'HOW TO PLEASE A WOMAN': 482, 'THE BANSHEES OF INISHERIN': 66405, 'THE DEVIL CONSPIRACY': 54300, 'BOY FROM HEAVEN': 1481, 'CREED III': 814341, 'IL COLIBRI': 2083, 'MUMMIES': 318765, 'CLOSE': 35626, 'HOLY SPIDER': 1648, 'BED REST': 59097, 'MAYBE I DO': 78549, 'LIEBESDINGS': 29, 'MY NEIGHBOR ADOLF': 7050, 'MARLOWE': 5367, 'KNOCK AT THE CABIN': 314415, 'THE OFFERING': 329171, 'BROKER': 6798, 'ROCK DOG 3: BATTLE THE BEAT': 25758, 'MATAR A PINOCHET': 251, "GOD'S CREATURES": 1669, 'MY FATHER HISTORIES': 276, 'THE TEXAS CHAIN SAW MASSACRE': 1836, 'THE WHALE': 409781, 'THE THREE MUSKETEERS: D’ARTAGNAN': 103590, 'ANT-MAN AND THE WASP: QUANTUMANIA': 2588946, 'COCAINE BEAR': 52410, 'GOLDA': 57628, 'DEATH OF NINTENDO': 35, 'HOURIA': 1908, 'LA NIÑA DE LA COMUNIÓN': 28826, 'UNE JEUNE FILLE QUI VA BIEN': 2318, '65': 230063, 'LEFT BEHIND: RISE OF THE ANTICHRIST': 156189, 'WOMEN TALKING': 26010, 'TWO WITCHES': 10453, 'BEAU IS AFRAID': 27430, 'EVIL DEAD RISE': 1021664, 'DUNGEONS & DRAGONS: HONOR AMONG THIEVES': 1046723, 'LOVE AGAIN': 67442, 'SCREAM VI': 1150220, 'THE POPE´S EXORCIST': 696010, 'HEAVEN IN HELL': 5800, 'CONSECRATION': 96714, 'THE SUPER MARIO BROS. MOVIE': 6235953, 'DEMON SLAYER: TO THE SWORDSMITH VILLAGE': 148205, 'AIR': 175232, 'SPINNING GOLD': 8712, 'BOOK CLUB: THE NEXT CHAPTER': 32690, 'FAST X': 6132354, 'RENFIELD': 40259, 'BOY GEORGE AND CULTURE CLUB “ONE WORLD, ONE LOVE”': 14, 'RODEO': 264, 'SONS OF RAMSÉS': 406, 'THE FIVE DEVILS': 393, 'EN ROUE LIBRE': 1384, 'IN FROM THE SIDE': 1677, 'ONE TRUE LOVES': 7796, 'SEA OF TIME': 889, 'SKINAMARINK': 1265, 'THE BLACK DEMON': 27091, 'MAFIA MAMMA': 19155, 'THE RITUAL KILLER': 9692, 'SUZUME': 44738, 'SPIDER-MAN: ACROSS THE SPIDER-VERSE': 3328797, 'CHAMPIONS': 4619, 'KANDAHAR': 53356, 'THE NIGHT 12TH': 1303, 'STRAYS': 87596, 'FINNICK': 62627, 'SADAKO DX': 75422, 'PACIFICTION': 307, 'KNIGHTS OF THE ZODIAC': 243516, 'LOST TRANSPORT': 1768, 'À PROPOS DE JOAN': 9601, 'NO BEARS': 3647, 'THE PORTABLE DOOR': 26728, 'EL ULTIMO LLAMADO DE MARÍA': 21056, 'EVOLUTION': 532, 'ABOUT MY FATHER': 12046, 'THE LITTLE MERMAID': 3987722, 'THE BOOK OF WONDERS': 5031, 'NO HARD FEELINGS': 141823, 'GUARDIANS OF THE GALAXY VOL. 3': 4211764, 'ARGONUTS': 47309, 'INSIDIOUS: THE RED DOOR': 736537, 'THE LAST BUS': 5038, 'THE STORY OF MY WIFE': 2104, 'EO': 2251, 'JOY RIDE': 47512, 'NOS LEVANTAREMOS AL ALBA': 6568, 'AFTER EVERYTHING': 85002, 'TALK TO ME': 752308, 'TO CATCH A KILLER (MISANTHROPE)': 32743, 'THE FLASH': 1825487, 'MEDUSA DELUXE': 1138, 'PASSAGES': 4851, 'ROGER WATERS LIVE - THIS IS NOT A DRILL': 5631, 'EQUALIZER 3': 665218, 'GRAN TURISMO': 406623, 'TRANSFORMERS: RISE OF THE BEASTS': 1285056, 'SWORD ART ONLINE THE MOVIE - PROGRESSIVE- SCHERZO OF DEEP NIGHT': 1953, 'THE BOOGEYMAN': 74456, 'TOMORROW X TOGETHER WORLD TOUR ACT: SWEET MIRAGE IN LA : LIVE VIEWING': 8054, 'ASTEROID CITY': 33210, 'THE LAST VOYAGE OF THE DEMETER': 78502, 'OPPENHEIMER': 2808153, 'RUBY GILLMAN TEENAGE KRAKEN': 100695, "SUGA - AGUST D TOUR 'D-DAY' IN JAPAN: LIVE VIEWING": 14549, 'ELEMENTAL': 3985017, 'CATS IN THE MUSEUM': 88021, 'LA SYNDICALISTE': 3063, 'J-HOPE IN THE BOX': 5296, 'SUGA: ROAD TO D-DAY': 6851, 'MISSION: IMPOSSIBLE - DEAD RECKONING PART ONE': 1820040, 'INDIANA JONES AND THE DIAL OF DESTINY': 964624, 'MON CRIME': 12398, 'THE EXPENDABLES 4': 474533, 'IT LIVES INSIDE': 148764, 'BARBIE': 10238598, 'BLUE BEETLE': 2015562, 'BLUE JEAN': 1577, 'FOGO FÁTUO': 500, 'THE MEG 2': 1197780, 'TIRAILLEURS': 2266, 'WONKA': 1723012, 'ALL FUN AND GAMES': 193315, 'MAVKA: THE FOREST SONG': 16406, 'RHEINGOLD': 818, 'WINNIE-THE-POOH: BLOOD AND HONEY': 27968, 'RETRIBUTION': 39866, 'HYPNOTIC': 135372, 'ONDE FICA ESTA RUA? OU SEM ANTES NEM DEPOIS': 127, 'DISCO BOY': 433, 'ALMA VIVA': 1168, 'TERRA QUE MARCA': 110, 'ÁGUAS DO PASTAZA': 139, 'THE HAUNTING OF THE QUEEN MARY': 60614, 'HAUNTED MANSION': 108810, 'THE FIRST SLAM DUNK': 4958, 'LA DERNIÈRE REINE': 936, 'THE ESTATE': 2258, 'BLACKBERRY': 4971, 'ZEBY NIE BYLO SLADÓW': 25, 'EL CIELO NO PUEDE ESPER@R': 32980, 'SAINT MICHAEL - MEET THE ANGEL': 37876, 'LAILA IN HAIFA': 1390, '97 MINUTES': 4270, 'WILDFLOWER': 2308, 'MY FAIRY TROUBLEMAKER': 79397, 'QUICKSAND': 3719, 'TEENAGE MUTANT NINJA TURTLES: MUTANT MAYHEM': 673020, 'THE DIVE': 15585, 'ITHAKA': 976, 'LE OTTO MONTAGNE': 6052, 'MAMAMOO: MY CON THE MOVIE': 1075, 'KANG DANIEL: MY PARADE': 77, 'ODESZA: THE LAST GOODBYE CINEMATIC EXPERIENCE': 251, 'AN CAILÍN CIÚIN': 3944, 'DUMB MONEY': 23277, 'NAPOLEON': 775802, 'COBWEB': 54447, 'JULES': 849, 'VIDBLYSK': 311, 'RIDE ON': 1114, 'TELL IT LIKE A WOMAN': 367, 'METALLICA M72 WORLD TOUR LIVE FROM TX NIGHT ONE': 7463, 'A HAUNTING IN VENICE': 277599, 'ARISTOTLE AND DANTE DISCOVER THE SECRET OF THE UNIVERSE': 9844, 'SAW X': 912603, 'IL BOEMO': 486, 'SOUND OF FREEDOM': 2597889, 'THANKSGIVING': 163869, 'THE CREATOR': 270620, "THE MARSH KING'S DAUGHTER": 16560, 'THE NUN 2': 2839181, 'THE EXORCIST: BELIEVER': 694281, 'BANK OF DAVE': 146, "FIVE NIGHTS AT FREDDY'S": 2777366, 'AQUAMAN AND THE LOST KINGDOM': 1331249, 'TROLLS BAND TOGETHER': 1417672, 'CARLOS: THE SANTANA JOURNEY GLOBAL PREMIERE': 285, 'EXTRAÑA FORMA DE VIDA': 23234, 'GLUPCY': 341, 'IU CONCERT: THE GOLDEN HOUR': 1042, 'LA MAISON': 3521, 'ARRÊTE AVEC TES MENSONGES': 222, 'NEFARIOUS': 8234, 'OLDBOY': 7311, 'KILLERS OF THE FLOWER MOON': 418794, 'NYAD': 132, 'PAW PATROL: THE MIGHTY MOVIE': 1385168, 'NOSTALGIA': 1075, 'LES ENFANTS DES AUTRES': 859, 'LILLE ALLAN - DEN MENNESKELIGE ANTENNE': 5226, 'LES ÂMES SOEURS': 358, 'LE NOUVEAU JOUET': 1300, 'THEY SHOT THE PIANO PLAYER': 2168, 'BRADO': 175, 'MY BIG FAT GREEK WEDDING 3': 12293, 'THE KILLER': 2525, 'TAYLOR SWIFT - THE ERAS TOUR': 185601, 'THE MARVELS': 1188572, 'EL AÑO DEL TIGRE': 157, 'KAIBUTSU': 13478, 'MAESTRO': 6087, 'RABIN, THE LAST DAY': 3451, 'THE NUTCRACKER AND THE MAGIC FLUTE': 34267, 'LA STRANEZZA': 705, 'LEONORA ADDIO': 280, 'FALLEN LEAVES': 11459, 'HOW TO HAVE SEX': 1148, 'ROTER HIMMEL': 4200, 'SAMSARA': 575, 'LORD OF MISRULES': 6397, 'SILENT NIGHT': 24708, 'THE HUNGER GAMES – BALLAD OF SONGBIRDS AND SNAKES': 1949600, 'PICCOLO CORPO': 43, 'LE RETOUR': 169, 'MIGRATION': 19, 'LE THÉORÈME DE MARGUERITE': 991, "L'ÉTÉ DERNIER": 1444, 'DIGIMON ADVENTURE 02: THE BEGINNING': 29377, 'LA SOCIEDAD DE LA NIEVE': 486, 'THE THREE MUSKETEERS: MILADY': 19051, 'THE MEAN ONE': 1283, 'GODZILLA MINUS ONE': 216849, 'NEXT GOAL WINS': 2383, 'RENAISSANCE: A FILM BY BEYONCÉ': 153244, 'SOFTIE': 233, 'LA LIGNE': 543, 'NCT NATION: TO THE WORLD IN CINEMAS': 4215, 'JOURNEY TO BETHLEHEM': 8247, 'PRISCILLA': 7904, "SEVENTEEN TOUR 'FOLLOW' TO JAPAN: LIVE VIEWING": 6140, 'THE CHOSEN': 114826}

In [47]:
# Questão 2: Qual o filme de maior bilheteria em 2023, por país de origem?
# Criando banco de dados

paises = []
filmes = []
for i in range(0,515):
    if bd_filmes.loc[i,"pais_origem"] not in paises:
        pais = bd_filmes.loc[i,"pais_origem"]
        filmes_pais = bd_filmes[bd_filmes['pais_origem'] == pais]
        filme_atual = filmes_pais.iloc[0]['titulo_original']
        for i in filmes_pais['titulo_original']:
            if dic_bilheteria[filme_atual]<dic_bilheteria[i]:
                filme_atual = i
        filmes.append(filme_atual)
        paises.append(pais)

dados_2 = {
    'Países' : paises,
    'Filmes' : filmes
}
df_bilheteria_paises = pd.DataFrame(dados_2)
display(df_bilheteria_paises)

                    Países                                  Filmes
0                   BRASIL                             NOSSO SONHO
1                 PORTUGAL                          A ÚLTIMA FESTA
2                ARGENTINA                       BEM-VINDA VIOLETA
3                   FRANÇA        THE THREE MUSKETEERS: D’ARTAGNAN
4                   CANADÁ            PAW PATROL: THE MIGHTY MOVIE
5           ESTADOS UNIDOS                                  BARBIE
6              REINO UNIDO                                   GOLDA
7               INGLATERRA                                NAPOLEON
8            CORÉIA DO SUL                       DECISION TO LEAVE
9                     PERU        AINBO - THE SPIRIT OF THE AMAZON
10                ALEMANHA                     THE AMAZING MAURICE
11                   JAPÃO                   KNIGHTS OF THE ZODIAC
12                   CHINA       OPERATION FORTUNE: RUSE DE GUERRE
13                 ESPANHA                                 MUMMIES
14                 POLÔNIA                          HEAVEN IN HELL
15                 BÉLGICA                                   CLOSE
16                 ESTÔNIA                                FIREBIRD
17                  RÚSSIA                                 FINNICK
18                 ÁUSTRIA                                 CORSAGE
19                   ÍNDIA                        THE TIGER'S NEST
20               AUSTRÁLIA                              TALK TO ME
21        REPÚBLICA TCHECA                    THE DEVIL CONSPIRACY
22               DINAMARCA  LILLE ALLAN - DEN MENNESKELIGE ANTENNE
23                  SUÉCIA                              IL COLIBRI
24                COLÔMBIA                       MY NEIGHBOR ADOLF
25                   CHILE                 LA SOCIEDAD DE LA NIEVE
26               FILIPINAS                       DEATH OF NINTENDO
27                 HOLANDA                             SEA OF TIME
28    REPÚBLICA DOMINICANA                         THE BLACK DEMON
29                     IRÃ                                NO BEARS
30                  PANAMÁ              EL ULTIMO LLAMADO DE MARÍA
31  EMIRADOS ÁRABES UNIDOS                            THE LAST BUS
32   BELARUS (BIELORUSSIA)                      CATS IN THE MUSEUM
33         CORÉIA DO NORTE                     SUGA: ROAD TO D-DAY
34                 ARGÉLIA                       LA DERNIÈRE REINE
35                  ITÁLIA                        LE OTTO MONTAGNE
36                 IRLANDA                         AN CAILÍN CIÚIN
37                 UCRÂNIA                                VIDBLYSK
38               ESLOVÊNIA                           PICCOLO CORPO
39                   SUÍÇA                                LA LIGNE

## PARTE 2: Análise estatística dos dados